// Setting the login contstants
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
// Setting the logout contstant
export const USER_LOGOUT = "USER_LOGIN_LOGOUT";
// Setting the user register contstants
export const USER_REGISTER_REQUEST = "USER_LOGIN_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_REGISTER_FAIL = "USER_LOGIN_FAIL";
// Setting the user details contstants
export const USER_DETAILS_REQUEST = "USER_LOGIN_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_DETAILS_FAIL = "USER_LOGIN_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";
// Setting the update user profile contstants
export const USER_UPDATE_PROFILE_REQUEST = "USER_LOGIN_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_LOGIN_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_LOGIN_RESET";

export const USER_LIST_DETAILS_REQUEST = "USER_ADMIN_DETAILS_REQUEST";
export const USER_LIST_DETAILS_SUCCESS = "USER_ADMIN_DETAILS_SUCCESS";
export const USER_LIST_DETAILS_FAIL = "USER_ADMIN_DETAILS_FAIL";
export const USER_LIST_DETAILS_RESET = "USER_ADMIN_DETAILS_RESET";
