# Generated by Django 3.1.4 on 2021-08-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='product_id',
        ),
    ]
