# Generated by Django 3.1.4 on 2021-08-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210805_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
    ]
