# Generated by Django 3.1.4 on 2021-08-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210805_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
